### ISSUE TITLE
Redis dependency not in docker compose example in readme

### ISSUE THREAD

**Issue by barakplasma** [rishikanthc/Scriberr#1]
I see that scriberr depends on redis being installed for the job queue,but redis isn't in he docker compose yml. Have you considered reusing the existing pocketbase backend in scriberr as a queue using https://github.com/joseferben/pocketbase-queue/ instead ?

**Comment by rishikanthc** [comment]
Redis is installed in the container itself. Checkout the Dockerfile if you would like to know more on how redis is invoked. It's in one of the scripts.
I did not know of pocketbase-queue until now. It looks promising. I just need a basic job queue as of now but I'll take a look at this and consider.

Closing this as it's not exactly an issue.

**Comment by barakplasma** [comment]
I don't see a Dockerfile in the repo as of 22d65be313f22d609f25953c76addea6966c3ec7 , nor any installation of redis. Maybe you forgot to upload the Dockerfile? I see that you did upload an image to ghcr, but it doesn't have any sources 
![image](https://github.com/user-attachments/assets/92601341-fb3a-480d-9c91-b4f0e8c7a6d8)

**Comment by rishikanthc** [comment]
My bad. The dockerfile should be available on the repo now

**Comment by rishikanthc** [comment]
Also feel free to create a PR to pull out the redis as a separate container.. Would love to get some help on this. I know the containerization has been done very crudely.

**Comment by barakplasma** [comment]
The https://github.com/rishikanthc/Scriberr/blob/main/docker-compose.ollama.yaml loads redis properly, good enough for me anyway.
