### ISSUE TITLE
NVIDIA Support GPU for Unraid server

### ISSUE THREAD

**Issue by Suspect-byte** [rishikanthc/Scriberr#12]
Hi,

Amazing work thanks for that. I have a problem I want to add my gpu to Scriberr:
What I have done:
- Installed the NVIDIA Drivers on unraid
-   NVIDIA_VISIBLE_DEVICES added as a variable
-  NVIDIA_DRIVER_CAPABILITIES added as variable 

Still no work sadly. What can I do differently? Or is there already a docker with support for NVIDIA GPU's

Thanks in advance

**Comment by rishikanthc** [comment]
Yeah that wouldn't work. So for nvidia you support the image should be compiled with a base image that has cuda installed. And also need to set a flag while compiling whisper.cpp
I'll compile an image with nvidia support and push soon. 

However if you need it badly and are familiar with dockerfiles then simply do the following. Change the base image to an nvidia image with cuda depending on the gpu you have installed. Then add commands to install node. In the whisper GitHub there's a small section on nvidia gpu which mentions the flag to be set. Add that to the compile command for whisper in the dockerfile before running make. 
That should do it. 

I'll try to push an image out soon. Sorry for the wait.

**Comment by Suspect-byte** [comment]
@rishikanthc Thank you, Im not very good with dockerfiles have tried a few. I will ask my good old friend ChatGPT or Claude. To fix it for me maybe I will learn something from it. Otherwise I will just wait for your image ;)

**Comment by rishikanthc** [comment]
Hey just wanted to let you know that nvidia gpu images are available now. Let me know if you face issues.

**Comment by Suspect-byte** [comment]
@rishikanthc Hey thanks for making it!!! I was out of town for a while. I have been trying to do everything. I enabled the nvidia support with true added the same comments as above and with parameters i added --gpu-all. I used this image, ghcr.io/rishikanthc/scriberr:0.3.0-nvidia, but im getting alot of errors....

**Comment by Suspect-byte** [comment]
My error log is this:

`==========

== CUDA ==

==========

CUDA Version 12.2.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.

By pulling and using the container, you accept the terms and conditions of this license:

https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.

   Use the NVIDIA Container Toolkit to start this container with GPU support; see

   https://docs.nvidia.com/datacenter/cloud-native/ .

Creating admin with email: --------------

PocketBase URL: http://--------------

> scriberr@0.0.1 build


> vite build

vite v5.4.7 building SSR bundle for production...

transforming...

3:03:07 PM [vite-plugin-svelte] /app/src/lib/components/FilePanel.svelte:366:7 A11y: Avoid using autofocus

364:               class="h-[30px] w-[300px] rounded-md border border-carbongray-300 p-1 focus:outline-none focus:ring-2 focus:ring-carbongray-800 focus:ring-offset-2 focus:ring-offset-white disabled:bg-carbongray-50 dark:bg-carbongray-700 disabled:dark:bg-carbongray-600"

365:               on:keydown={handleKeydownRecord}

366:               autofocus

                   ^

367:               disabled={renameLoading}

368:             />

3:03:07 PM [vite-plugin-svelte] /app/src/lib/components/FilePanel.svelte:374:5 A11y: <div> with dblclick handler must have an ARIA role

372:           </div>

373:         {:else}

374:           <div class="text-4xl" on:dblclick={renameTempl}>

               ^

375:             {selected?.title}

376:           </div>

3:03:07 PM [vite-plugin-svelte] /app/src/lib/components/FilePanel.svelte:396:7 A11y: Avoid using autofocus

394:               class="h-[30px] w-[300px] rounded-md border border-carbongray-300 p-1 focus:outline-none focus:ring-2 focus:ring-carbongray-800 focus:ring-offset-2 focus:ring-offset-white disabled:bg-carbongray-50 dark:bg-carbongray-700 disabled:dark:bg-carbongray-600"

395:               on:keydown={handleKeydown}

396:               autofocus

                   ^

397:               disabled={renameLoading}

398:             />

3:03:07 PM [vite-plugin-svelte] /app/src/lib/components/FilePanel.svelte:404:5 A11y: <div> with dblclick handler must have an ARIA role

402:           </div>

403:         {:else}

404:           <div class="text-4xl" on:dblclick={renameTempl}>

               ^

405:             {selectedTemplate?.title}

406:           </div>

3:03:08 PM [vite-plugin-svelte] /app/src/lib/components/UploadPane.svelte:84:1 A11y: visible, non-interactive elements with an on:click event must be accompanied by a keyboard event handler. Consider whether an interactive element such as <button type="button"> or <a> might be more appropriate. See https://svelte.dev/docs/accessibility-warnings#a11y-click-events-have-key-events for more details.

82: <div class="w-full">

83:   

84:   <div

      ^

85:     class="my-4 flex h-[150px] w-full cursor-pointer items-center justify-center border border-dashed border-carbongray-200 text-carbongray-300 dark:border-carbongray-600"

86:     on:dragover={handleDragOver}

3:03:08 PM [vite-plugin-svelte] /app/src/lib/components/UploadPane.svelte:84:1 A11y: <div> with dragover, drop, click handlers must have an ARIA role

82: <div class="w-full">

83:   

84:   <div

      ^

85:     class="my-4 flex h-[150px] w-full cursor-pointer items-center justify-center border border-dashed border-carbongray-200 text-carbongray-300 dark:border-carbongray-600"

86:     on:dragover={handleDragOver}

3:03:08 PM [vite-plugin-svelte] /app/src/lib/components/Processing.svelte:14:1 Unused CSS selector ".dot-container"

12: 

13: <style>

14:   .dot-container {

      ^

15:     display: inline-flex;

16:     gap: 5px;

src/routes/api/files/+server.ts (1:9): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/files/+server.ts".

src/routes/api/jobs/configure/+server.ts (1:9): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/jobs/configure/+server.ts".

src/routes/api/jobs/configure/[id]/+server.ts (1:9): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/jobs/configure/[id]/+server.ts".

src/routes/api/records/+server.ts (1:15): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/records/+server.ts".

src/routes/api/records/[id]/+server.ts (1:15): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/records/[id]/+server.ts".

src/routes/api/settings/+server.ts (1:15): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/settings/+server.ts".

src/routes/api/templates/+server.ts (1:15): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/templates/+server.ts".

src/routes/api/templates/[id]/+server.ts (1:15): "RequestHandler" is not exported by "node_modules/@sveltejs/kit/src/exports/index.js", imported by "src/routes/api/templates/[id]/+server.ts".

"resolve" is imported from external module "chart.js/helpers" but never used in "src/hooks.server.ts".

"execSync" and "spawn" are imported from external module "child_process" but never used in "src/lib/wizardQueue.ts" and "src/lib/queue.ts".

✓ 2141 modules transformed.

rendering chunks...

node:internal/event_target:1090

  process.nextTick(() => { throw err; });

                           ^

ClientResponseError 400: Failed to authenticate.

    at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async AdminService.authWithPassword (file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:10912)

    at async file:///app/.svelte-kit/output/server/chunks/wizardQueue.js:12:1 {

  url: 'http://10.10.60.1:5170/api/admins/auth-with-password',

  status: 400,

  response: { code: 400, message: 'Failed to authenticate.', data: {} },

  isAbort: false,

  originalError: {

    url: 'http://10.10.60.1:5170/api/admins/auth-with-password',

    status: 400,

    data: { code: 400, message: 'Failed to authenticate.', data: {} }

  }

}

Node.js v22.10.0

npm notice

npm notice New patch version of npm available! 10.9.0 -> 10.9.1

npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.1

npm notice To update run: npm install -g npm@10.9.1

npm notice

node:internal/modules/cjs/loader:1252


  throw err;

  ^

Error: Cannot find module '/app/build'

    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)

    at Function._load (node:internal/modules/cjs/loader:1075:27)

    at TracingChannel.traceSync (node:diagnostics_channel:315:14)

    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)

    at node:internal/main/run_main_module:36:49 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}

Node.js v22.10.0`
