### ISSUE TITLE
Redis Connection issue

### ISSUE THREAD

**Issue by dpeet** [rishikanthc/Scriberr#22]
Similar to #1 if I use the docker-compose on the readme, I get this error and nothing seems to work

```
24-10-17 08:27:03 scriberr-1  | Error: connect ECONNREFUSED 127.0.0.1:6379
2024-10-17 08:27:03 scriberr-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
2024-10-17 08:27:03 scriberr-1  |   errno: -111,
2024-10-17 08:27:03 scriberr-1  |   code: 'ECONNREFUSED',
2024-10-17 08:27:03 scriberr-1  |   syscall: 'connect',
2024-10-17 08:27:03 scriberr-1  |   address: '127.0.0.1',
2024-10-17 08:27:03 scriberr-1  |   port: 6379
2024-10-17 08:27:03 scriberr-1  | }
```

```
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:beta-0.2
    ports:
      - "3000:3000"
      - "8080:8080" #Optionally expose DB UI
      - "9243:9243" #Optionally expose JobQueue UI
    environment:
      - OPENAI_API_KEY=[my-key-here]
      - POCKETBASE_ADMIN_EMAIL=admin@example.com
      - POCKETBASE_ADMIN_PASSWORD=password
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - SCRIBO_FILES=/scriberr
    volumes:
      - ./pb_data:/app/db
      - ./scriberr_data:/scriberr
```

**Comment by rishikanthc** [comment]
My apologies. Forgot to add redis to docker compose. Append this to your compose and try again

```
redis:
    image: redis:7-alpine
    volumes:
      - ./.dockerdata/redis:/data
```

**Comment by dpeet** [comment]
So adding that I had the same error.  I chucked it into chatgpt, and it suggested I use `redis` instead of `127.0.0.1`.   Here's the chat.  That seemed to work for me.


> The error message connect ECONNREFUSED 127.0.0.1:6379 indicates that the scriberr service is unable to connect to Redis on the specified host (127.0.0.1) and port (6379).
> 
> In your docker-compose.yml, you're defining two services: scriberr and redis. However, the environment variable REDIS_HOST=127.0.0.1 is pointing the scriberr service to try and connect to Redis on localhost (within the scriberr container), but Redis is running in a separate container.
> 
> Containers in a Docker network communicate with each other using their service names, not localhost. To fix this issue, update the REDIS_HOST environment variable in the scriberr service to use the service name of the Redis container (i.e., redis).
> 
> Here’s the updated part of your docker-compose.yml:
> 
> ```yaml
> 
> services:
>   scriberr:
>     environment:
>       - REDIS_HOST=redis
>       - REDIS_PORT=6379
> This will allow the scriberr service to communicate with the Redis service properly across containers. Docker Compose automatically sets up a network for the services, and the service name (redis) can be used as the hostname within the network.
> 
> ```
