### ISSUE TITLE
Transcription Fails After Uploading MP3 (Exit Code 132)

### ISSUE THREAD

**Issue by BranaHawk9** [rishikanthc/Scriberr#25]
Platform: **Ubuntu 22.04.5 LTS**

When uploading an MP3 file, the upload process starts but stops after a few seconds. The following error message appears in the Docker container logs:

> Done: rr-1  | stderr: 
> scriberr-1  | stderr: 100%
> scriberr-1  | Read 14834022 frames
> scriberr-1  | Generated 57946 points
> scriberr-1  | Output file: /scriberr/audio/plfi8hr5fai1l2v/plfi8hr5fai1l2v.mp3.json
> scriberr-1  | 
> scriberr-1  | stderr: Done
> scriberr-1  | 
> scriberr-1  | stderr: Illegal instruction (core dumped)
> scriberr-1  | 
> scriberr-1  | Error: Command failed with exit code 132
> scriberr-1  |     at ChildProcess.<anonymous> (file:///app/build/server/chunks/queue-Ckp2S0FN.js:43898:16)
> scriberr-1  |     at ChildProcess.emit (node:events:531:35)
> scriberr-1  |     at maybeClose (node:internal/child_process:1104:16)
> scriberr-1  |     at ChildProcess._handle.onexit (node:internal/child_process:304:5)

[docker-compose.txt](https://github.com/user-attachments/files/17439460/docker-compose.txt)
[log.txt](https://github.com/user-attachments/files/17439461/log.txt)

**Comment by rishikanthc** [comment]
Is this with auto diarization enabled or disabled ?

**Comment by BranaHawk9** [comment]
That's with auto diarization disabled. With it enabled I get this:

> Done: 99%1  | stderr: 
> Done: 100%  | stderr: 
> scriberr-1  | Read 14834022 frames
> scriberr-1  | Generated 57946 points
> scriberr-1  | Output file: /scriberr/audio/3hdawmyaifri2c0/3hdawmyaifri2c0.mp3.json
> scriberr-1  | 
> scriberr-1  | stderr: Done
> scriberr-1  | 
> scriberr-1  | stdout: Loading pyannote pipeline from /Users/richandrasekaran/Code/Scriberr/diarize/models/pyannote_diarization_config.yaml...
> scriberr-1  | Changing working directory to /Users/richandrasekaran/Code/Scriberr/diarize
> scriberr-1  | 
> scriberr-1  | stderr: Traceback (most recent call last):
> scriberr-1  |   File "/app/./diarize/local.py", line 47, in <module>
> scriberr-1  |     pipeline = load_pipeline_from_pretrained(PATH_TO_CONFIG)
> scriberr-1  |   File "/app/./diarize/local.py", line 37, in load_pipeline_from_pretrained
> scriberr-1  |     os.chdir(cd_to)
> scriberr-1  | FileNotFoundError: [Errno 2] No such file or directory: '/Users/richandrasekaran/Code/Scriberr/diarize'
> scriberr-1  | 
> scriberr-1  | Error: Command failed with exit code 1
> scriberr-1  |     at ChildProcess.<anonymous> (file:///app/build/server/chunks/queue-Ckp2S0FN.js:43898:16)
> scriberr-1  |     at ChildProcess.emit (node:events:531:35)
> scriberr-1  |     at maybeClose (node:internal/child_process:1104:16)
> scriberr-1  |     at ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by rishikanthc** [comment]
This error makes sense. I'm a little confused by the non diarized one. I'll debug this.

**Comment by rishikanthc** [comment]
Can you try the latest release 0.3.0 ? I have changed the docker base image and built new packages. I have tested them on my machine as best as I can. Let me know if this one works for you.

**Comment by BranaHawk9** [comment]
I'm not getting these errors anymore on 0.3.0. Everything starts up without errors and the new UI works correctly. I've still been unable to complete a transcription though. Everything seems to fail at 35%. 

From the Bull Dashboard:
```
Diarization completed successfully
Parsed RTTM file for record vbltk4gafoxoic3
stderr: whisper_init_from_file_with_params_no_state: loading model from '/models/ggml-tiny.en.bin'
whisper_init_from_file_with_params_no_state: failed to open '/models/ggml-tiny.en.bin'
error: failed to initialize whisper context
Error: Command failed with exit code 3
```
From the docker logs:
```
stderr: whisper_init_from_file_with_params_no_state: loading model from '/models/ggml-tiny.en.bin'
scriberr-1    | whisper_init_from_file_with_params_no_state: failed to open '/models/ggml-tiny.en.bin'
scriberr-1    | error: failed to initialize whisper context
scriberr-1    | 
scriberr-1    | Error: Command failed with exit code 3
scriberr-1    |     at ChildProcess.<anonymous> (file:///app/build/server/chunks/queue-Bdtmtx2w.js:43900:16)
scriberr-1    |     at ChildProcess.emit (node:events:530:35)
scriberr-1    |     at maybeClose (node:internal/child_process:1104:16)
scriberr-1    |     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Should I raise a new issue for this? Or could it be a configuration issue on my end?

**Comment by rishikanthc** [comment]
If you can share your docker compose I can also take a look at that.

**Comment by BranaHawk9** [comment]
I've done some additional testing and I believe that error was caused by the model not downloading correctly as you suggested.
I've not been able to reproduce it and the transcription now works correctly for me. It completes to 100% and the transcription is viewable in the web UI. Thanks for the help.
