### ISSUE TITLE
Speaker detection

### ISSUE THREAD

**Issue by upamanyudas** [rishikanthc/Scriberr#8]
having the ability for speaker(s) detection would be great!

`extra context : currently use Descript. would love to help turn Scriberr to a more powerful self-hosted alternative.`

**Comment by rishikanthc** [comment]
I'm planning to add speaker detection. I had looked around and settled on pyannote.. More than open to suggestions.. Feel free to submit PRs as well.

**Comment by rishikanthc** [comment]
Speaker detection and diarization has been added in the new release 0.2.0
Check it out :)
